apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: saproject
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: saproject
        visualize: "true"
    spec:
      containers:
        - name: saproject-pod
          image: makhanov27/saproject
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: saproject-service
spec:
  selector:
    app: saproject
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP